Travail sur la timeline du hackathon et l'évolution des dataviz Lena
EPgg92/article_commun_gag pull request #6
Opened 2023-06-03 23:58 UTC by lenaMK

2023-06-03 23:59 UTC, lenaMK commented
désolée j'avais pas pensé à regarder ton pr d'abord, du coup je crains que ça crée un chaos.. on verra :crossed_fingers:

2023-06-06 23:53 UTC, EPgg92 requested changes
Peux-tu rollback ton changement sur les `’` je prends note qu'il faudra les remplacer par des `'` avec un single line command du genre `tr \' "’"`!

2023-06-06 23:53 UTC, EPgg92 commented on article/article_commun.md
> +```
Either:

```txt
```js
[
  {
    name: 'chat',
    ordre: '5.0',
    cat: 'domestique',
    url: 'https://anthologiagraeca.org/passages/urn:cts:greekLit:tlg7000.tlg001.ag:5.3/'
  },
  {
    name: 'chien',
    ordre: '5.23',
    cat: 'domestique',
    url: 'https://anthologiagraeca.org/passages/urn:cts:greekLit:tlg7000.tlg001.ag:5.3/'
  },
  {
    name: 'baleine',
    ordre: '5.117',
    cat: 'océan',
    url: 'https://anthologiagraeca.org/passages/urn:cts:greekLit:tlg7000.tlg001.ag:5.3/'
  },
  {
    name: 'cheval',
    ordre: '5.250',
    cat: 'loisir',
    url: 'https://anthologiagraeca.org/passages/urn:cts:greekLit:tlg7000.tlg001.ag:5.3/'
  }
]
\```
```

or 

```txt
```json
{
  "keywords": [
    {
      "name": "chat",
      "ordre": "5.0",
      "cat": "domestique",
      "url": "https://anthologiagraeca.org/passages/urn:cts:greekLit:tlg7000.tlg001.ag:5.3/"
    },
    {
      "name": "chien",
      "ordre": "5.23",
      "cat": "domestique",
      "url": "https://anthologiagraeca.org/passages/urn:cts:greekLit:tlg7000.tlg001.ag:5.3/"
    },
    {
      "name": "baleine",
      "ordre": "5.117",
      "cat": "océan",
      "url": "https://anthologiagraeca.org/passages/urn:cts:greekLit:tlg7000.tlg001.ag:5.3/"
    },
    {
      "name": "cheval",
      "ordre": "5.250",
      "cat": "loisir",
      "url": "https://anthologiagraeca.org/passages/urn:cts:greekLit:tlg7000.tlg001.ag:5.3/"
    }
  ]
}
\```
```

2023-06-06 23:53 UTC, EPgg92 commented on todo.md
> +  -  🦊 j'ai commencé à mettre des commentaires sur l'API dans l'encadré, tu iras voir ce qui te convient ou pas et ce que tu voudrais ajouter
Oui on doit faire un retour critique qui s'incorpore mieux au reste de l'article !

2023-06-07 16:06 UTC, Mmellet approved these changes

2023-06-07 16:22 UTC, EPgg92 approved these changes

2023-06-07 16:22 UTC, merged